// Generated by `pnpm --filter @petroglyph/event-catalogue generate-catalogue`.
// Do not edit by hand: declare the event in its owning package and regenerate.
import type { CatalogueEntry } from "./catalogue-entry.js";
import { fileDeletedEvent, fileStagedEvent } from "@petroglyph/staging-contracts";

export const eventCatalogue: CatalogueEntry[] = [
  {
    type: "petroglyph.file.deleted",
    dataschema: "https://schemas.petroglyph.dev/file-deleted/v1.json",
    parse: (document) => fileDeletedEvent.parse(document),
  },
  {
    type: "petroglyph.file.staged",
    dataschema: "https://schemas.petroglyph.dev/file-staged/v1.json",
    parse: (document) => fileStagedEvent.parse(document),
  },
];
